import Head from "next/head";
import styles from "../styles/Home.module.css";
import About from "../components/About";
import CanvasDraw from "../components/atoms/canvas";
import CardList from "components/CardList";
import Projects from "components/Projects";

export default function Home() {
  return (
    <>
      <CanvasDraw />
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Yashwant Dangi</h1>
          <p className={styles.description}>Full-Stack Developer</p>
        </main>
        <About />
        <CardList />
        <Projects />
      </div>
    </>
  );
}
